
Info<< "rho max/min : "
        << max(rho).value() << " "
        << min(rho).value() << endl;
Info<< "mut max/min : "
        << max(turbulence->mut()).value() << " "
        << min(turbulence->mut()).value() << endl;
    Info<< "muEff max/min : "
        << max(turbulence->muEff()).value() << " "
        << min(turbulence->muEff()).value() << endl;
    Info<< "K max/min : "
        << max(K).value() << " "
        << min(K).value() << endl;
Info<< "p max/min : "
        << max(p).value() << " "
        << min(p).value() << endl;
Info<< "p_rgh max/min : "
        << max(p_rgh).value() << " "
        << min(p_rgh).value() << endl;
Info<< "Z max/min : "
        << max(Z).value() << " "
        << min(Z).value() << endl;
Info<< "Zvar max/min : "
        << max(Zvar).value() << " "
        << min(Zvar).value() << endl;
Info<< "chi_st max/min : "
        << max(chi_st).value() << " "
        << min(chi_st).value() << endl;

Info<< "T max/min : "
        << max(T).value() << " "
        << min(T).value() << endl;

